name: Code style and static analysis

on:
    pull_request:
    push:
        branches: [ master, develop ]

jobs:
    php-cs-fixer:
        name: PHP-CS-Fixer
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2

            - name: Install dependencies
              run: composer install --no-progress --no-interaction --prefer-dist

            - name: Run script
              run: composer check-style

    phpstan:
        name: PHPStan
        runs-on: ubuntu-latest
        strategy:
          fail-fast: false
          matrix:
            php:
              - '7.2'
              - '7.3'
              - '7.4'
              - '8.0'
              - '8.1'
              - '8.2'
            coverage: [ 'none' ]
            monolog:
              - '^2.1'
              - '^3.0'
            include:
              - php: '8.1'
                monolog: '^3.0'
              - php: '8.2'
                monolog: '^3.0'
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2

            - name: Update package versions
              run: |
                composer require monolog/monolog:${{ matrix.monolog }} --no-update --no-scripts -W

            - name: Install dependencies
              run: composer install --no-progress --no-interaction --prefer-dist

            - name: Run script
              run: |
                php tools/prepare-configs.php;
                composer phpstan


    composer-validate:
        name: Composer validate
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2

            - name: Install dependencies
              run: composer install --no-progress --no-interaction --prefer-dist

            - name: Run script
              run: composer composer-validate
